#!/bin/bash

pkgname="awesome-WM"

pkgdescription="awesome window manager"

pkgsource="https://github.com/awesomeWM/awesome.git"

dependencies=""

pkginstall="make"

pkmgr=""

pkgconfig () {
	sudo mv ~/awesome /usr/local/src/hexpmg-list && cd /usr/local/src/hexpmg-list/awesome && make && sudo make install	
}


git clone $pkgsource

pkgconfig
