#!/bin/sh

pkgname="awesome-WM"

pkgdescription="awesome window manager"

pkgsource="https://github.com/awesomeWM/awesome.git"

dependencies=""

pkginstall="make"

pkmgr=""

pkgconfig () {
	sudo mv ~/awesome /usr/local/src && cd /usr/local/src/awesome && make && sudo make install	
}


git clone $pkgsource

pkgconfig
