#!/bin/bash

pkgname='doom-emacs'

pkgdescription='An Emacs framework for the stubborn martian hacker'

pkgsource='https://github.com/emacs-mirror/emacs.git'

dependencies="build-essential texinfo libx11-dev libxpm-dev libjpeg-dev libpng-dev libgif-dev libtiff-dev libgtk2.0-dev libncurses-dev automake autoconf libgnutls28-dev"

pkginstall='source'


pkgconfig() {
	if command -v apt 2>/dev/null; then
		sudo apt install $dependencies && cd emacs && sudo make install && echo $pkgname >> ~/hexpmg-list


        fi


        if command -v dnf 2>/dev/null; then
		sudo apt install $dependencies && cd emacs && sudo make install && echo $pkgname >> ~/hexpmg-list


        fi


	if command -v pacman 2>/dev/null; then
		sudo apt install $dependencies && cd emacs && sudo make install && echo $pkgname >> ~/hexpmg-list


	fi

	git clone --depth 1 https://github.com/doomemacs/doomemacs ~/.emacs.d
        ~/.emacs.d/bin/doom install
}




git clone $pkgsource
	

pkgconfig
