#!/bin/bash

pkgname='emacs'

pkgdescription=''

pkgsource='https://github.com/emacs-mirror/emacs.git'

dependencies="build-essential texinfo libx11-dev libxpm-dev libjpeg-dev libpng-dev libgif-dev libtiff-dev libgtk2.0-dev libncurses-dev automake autoconf libgnutls28-dev"

pkginstall='source'


pkgconfig() {
	if [[ "$pkginstall" == "source" ]]; then
		sudo apt install $dependencies && cd emacs && sudo make install 
	fi
}




git clone $pkgsource
	

pkgconfig
