#!/bin/sh

pkgname='emacs'

pkgdescription=''

pkgsource='https://github.com/emacs-mirror/emacs.git'

dependencies="build-essential texinfo libx11-dev libxpm-dev libjpeg-dev libpng-dev libgif-dev libtiff-dev libgtk2.0-dev libncurses-dev automake autoconf libgnutls28-dev"

pkginstall='source'


pkgconfig() {
	if command -v apt 2>/dev/null; then
		sudo apt install $dependencies && sudo mv emacs /usr/local/src && cd /usr/local/src/emacs && sudo make install


        fi


        if command -v dnf 2>/dev/null; then
		sudo dnf install $dependencies && sudo mv emacs /usr/local/src && cd /usr/local/src/emacs && sudo make install


        fi


	if command -v pacman 2>/dev/null; then
		sudo pacman -S $dependencies && sudo mv emacs /usr/local/src && cd /usr/local/src/emacs && sudo make install


	fi



git clone $pkgsource
	

pkgconfig
