#!/bin/bash

pkgname='lutris'

pkgdescription='Lutris desktop client in Python / PyGObject'

pkgsource='https://github.com/lutris/lutris.git'

dependencies="python"

pkginstall='make'


pkgconfig () {
	if command -v apt 2>/dev/null; then
		sudo apt install python3

        fi


        if command -v dnf 2>/dev/null; then
		sudo dnf install python3

        fi


	if command -v pacman 2>/dev/null; then
		sudo pacman -S python3

	fi

	cd lutris && ./bin/lutris 

}



git clone $pkgsource
	

pkgconfig	
