#!/bin/bash

pkgname='pacstall'

pkgdescription='An AUR-inspired package manager for Ubuntu'


dependencies=""

pkginstall='script'


pkgconfig() {
	if [[ "$pkginstall" == "script" ]]; then
		sudo bash -c "$(curl -fsSL https://git.io/JsADh || wget -q https://git.io/JsADh -O -)"
	fi
}


echo "note to uninstall pacstall you need to run bash -c "$(curl -fsSL https://git.io/JEZbi || wget -q https://git.io/JEZbi -O -)" in your terminal" && sleep 2

pkgconfig

