#!/bin/bash

pkgname='pacstall'

pkgdescription='An AUR-inspired package manager for Ubuntu'


dependencies=""

pkginstall='script'


pkgconfig() {
	if [[ "$pkginstall" == "script" ]]; then
		sudo bash -c "$(curl -fsSL https://git.io/JsADh || wget -q https://git.io/JsADh -O -)" && echo $pkgname >> ~/hexpmg-list
	fi
}



pkgconfig

