#!/bin/bash

pkgname='pfetch'

pkgdescription='A pretty system information tool written in POSIX sh.'

pkgsource='https://github.com/dylanaraps/pfetch.git'

dependencies=""

pkginstall='make'


pkgconfig() {
	if [[ "$pkginstall" == "make" ]]; then
		sudo mv ~/pfetch /usr/local/src/hexpmg-list && cd /usr/local/src/hexpmg-list/pfetch && sudo make install && echo $pkgname >> ~/hexpmg-list 
	fi
}




git clone $pkgsource
	

pkgconfig	
