#!/bin/bash

pkgname="picom"

pkgdescription="A lightweight compositor for X11 (previously a compton fork) "

pkgsource="https://github.com/jonaburg/picom.git"

dependencies="cmake meson git pkg-config asciidoc libxext-dev libxcb1-dev libxcb-damage0-dev libxcb-xfixes0-dev libxcb-shape0-dev libxcb-render-util0-dev libxcb-render0-dev libxcb-randr0-dev libxcb-composite0-dev libxcb-image0-dev libxcb-present-dev libxcb-xinerama0-dev libxcb-glx0-dev libpixman-1-dev libdbus-1-dev libconfig-dev libgl1-mesa-dev  libpcre2-dev  libevdev-dev uthash-dev libev-dev libx11-xcb-dev"

pkginstall="make"

pkmgr=""

pkgconfig () {
	if command -v apt 2>/dev/null; then
		sudo apt install $dependencies && sudo mv ~/picom /usr/local/src/hexpmg-list && cd /usr/local/src/hexpmg-list/picom && git submodule update --init --recursive && meson --buildtype=release . build && ninja -C build && sudo ninja -C build install && echo $pkgname >> ~/hexpmg-list

        fi


        if command -v dnf 2>/dev/null; then
		sudo dnf install $dependencies && sudo mv ~/picom /usr/local/src/hexpmg-list && cd /usr/local/src/hexpmg-list/picom && git submodule update --init --recursive && meson --buildtype=release . build && ninja -C build && sudo ninja -C build install && echo $pkgname >> ~/hexpmg-list


	fi

        
	if command -v pacman 2>/dev/null; then
		sudo pacman -S $dependencies && sudo mv ~/picom /usr/local/src/hexpmg-list && cd /usr/local/src/hexpmg-list/picom && git submodule update --init --recursive && meson --buildtype=release . build && ninja -C build && sudo ninja -C build install && echo $pkgname >> ~/hexpmg-list


	fi		




}


git clone $pkgsource

pkgconfig
