#!/bin/sh

pkgname='ps-lookup'

pkgdescription='a simple and easy to use command line app that searches for the process you enter.'

pkgsource='https://github.com/hexisXz/ps-lookup.git'

dependencies=""

pkginstall='exe' 


pkgconfig() {
	if [ "$pkginstall" = "exe" ]; then
		bash -c "$(curl -fsSL https://raw.githubusercontent.com/hexisXz/ps-lookup/main/install.sh || wget -q https://raw.githubusercontent.com/hexisXz/ps-lookup/main/install.sh -o -)"

	fi
}




git clone $pkgsource
	

pkgconfig	






















