#!/bin/sh

pkgname='ps-lookup'

pkgdescription='a simple and easy to use command line app that searches for the process you enter.'

pkgsource='https://github.com/hexisXz/ps-lookup.git'

dependencies=""

pkginstall='exe' 


pkgconfig() {
	if [[ "$pkginstall" == "exe" ]]; then
		sh <(curl -v -L https://raw.githubusercontent.com/hexisXz/hexpmg/main/install.sh)

	fi
}




git clone $pkgsource
	

pkgconfig	






















