#!/bin/bash

pkgname='ps-lookup'

pkgdescription='a simple and easy to use command line app that searches for the process you enter.'

pkgsource='https://github.com/hexisXz/ps-lookup.git'

dependencies=""

pkginstall='exe' 


pkgconfig() {
	if [[ "$pkginstall" == "exe" ]]; then
		sudo mv ~/ps-lookup /usr/local/src/hexpmg-list && cd /usr/local/src/hexpmg-list/ps-lookup && chmod +x $pkgname && sudo mv $pkgname /bin && echo $pkgname >> ~/hexpmg-list 
	fi
}




git clone $pkgsource
	

pkgconfig	






















