#!/bin/sh

pkgname='btop'

pkgdescription='A monitor of resources'

pkgsource='https://github.com/aristocratos/btop.git'

dependencies="make"

pkginstall='make'


pkgconfig() {
	if $dependencies -v make >/dev/null; then
		git clone $pkgsource && sudo mv $pkgname /usr/local/src/ && cd /usr/local/src/$pkgname && make && sudo make install
        fi
}


pkgconfig
