#!/bin/sh

pkgname="exa"

pkgdescription="A modern replacement for ‘ls’."

pkgsource=""

dependencies="cargo"

pkginstall="pkgmgr"

pkmgr="cargo"

pkgconfig () {
	if command -v apt 2>/dev/null; then
		sudo apt install cargo && cargo install $pkgname

        fi


        if command -v dnf 2>/dev/null; then
		sudo dnf install rust cargo && cargo install $pkgname

        fi


	if command -v pacman 2>/dev/null; then
		sudo pacman -S rust && cargo install $pkgname

	fi


	if command -v xbps-install 2>/dev/null; then
		sudo xbps-install rust && cargo install $pkgname

	fi

}


pkgconfig






