#!/bin/sh

pkgname='bspwm'

pkgdescription='A tiling window manager based on binary space partitioning'

pkgsource='https://github.com/baskerville/bspwm.git'

dependencies="make"

pkginstall='make'


pkgconfig() {
	if command -v xbps-install 2>/dev/null; then
		sudo xbps-install make && git clone $pkgsource && sudo mv $pkgname /usr/local/src/ && make && sudo make install
	fi	


	if command -v apt 2>/dev/null; then
		sudo apt install make && git clone $pkgsource && sudo mv $pkgname /usr/local/src/ && make && sudo make install
	fi


	if command -v pacman 2>/dev/null; then
		sudo pacman -S make && git clone $pkgsource && sudo mv $pkgname /usr/local/src/ && make && sudo make install
	fi


	if command -v dnf 2>/dev/null; then
		sudo dnf install make && git clone $pkgsource && sudo mv $pkgname /usr/local/src/ && make && sudo make install
	fi
}


pkgconfig
