#!/bin/sh

pkgname='pfetch'

pkgdescription='A pretty system information tool written in POSIX sh.'

pkgsource='https://github.com/dylanaraps/pfetch.git'

dependencies=""

pkginstall='make'


pkgconfig() {
	if command -v xbps-install 2>/dev/null; then
		sudo xbps-install make && sudo mv pfetch /usr/local/src && cd /usr/local/src/pfetch && sudo make install 
	fi


	if command -v apt 2>/dev/null; then
		sudo apt install make && sudo mv pfetch /usr/local/src && cd /usr/local/src/pfetch && sudo make install 
	fi


	if command -v pacman 2>/dev/null; then
		sudo pacman -S make && sudo mv pfetch /usr/local/src && cd /usr/local/src/pfetch && sudo make install 
	fi


	if command -v dnf 2>/dev/null; then
		sudo dnf install make && sudo mv pfetch /usr/local/src && cd /usr/local/src/pfetch && sudo make install 
	fi
}




git clone $pkgsource
	

pkgconfig	
