#!/bin/sh

pkgname='wallset'

pkgdescription='A wallpaper manager that makes it possible to put videos as wallpaper'

pkgsource='https://github.com/terroo/wallset.git'

dependencies="make"

pkginstall='make'


pkgconfig() {
	if $dependencies -v make >/dev/null; then
		git clone $pkgsource && sudo mv $pkgname /usr/local/src/ && cd /usr/local/src/$pkgname && sudo ./install.sh --force
        fi
}


pkgconfig
